### ISSUE TITLE
bgp request body issue

### ISSUE THREAD

**Issue by vivek-metricdust** [STORDIS/orca_backend#24]
the request body of bgp is 
 request_body = {
            "mgt_ip": device_ip,
            "vrf_name": "default",
            "local_asn": 64500,
            "router_id": device_ip,
        }
where the "router_id": device_ip is forced to be same as mgt_ip and its ignoring the input from UI

**Comment by rahul-1475** [comment]
pr link: https://github.com/STORDIS/orca_backend/pull/66

It also includes fixes for issue: https://github.com/STORDIS/orca_backend/issues/24
