### ISSUE TITLE
Issue in deletion of VLAN properties - Vlan IP, Sag IP, description.

### ISSUE THREAD

**Issue by vivek-metricdust** [STORDIS/orca_backend#40]
For VLAN, The deletion for ip, description, Sag Ip is not working as there should be a separate API need to be called i.e, Delete api
as it is hard to call multiple API from the frontend this must be handled in backed.
When the value is null those must be deleted.

**Comment by rahul-1475** [comment]
- Sending None and empty string values in a PUT request does not indicate the intention to delete. Additionally, for creation, if a value is empty, deletion cannot occur before creation.
- This issue needs to be handled in the frontend by using separate JSON payloads for DELETE and PUT operations.

**Comment by vivek-metricdust** [comment]
This issue is not only respective to vlans also must be handled to all other config which has description, ip address or other values.

**Comment by vivek-metricdust** [comment]
issue is fixed and PR are created. Issue has library, backend and UI changes

- Library - [Issue in deletion of vlan properties - lib - #40 STORDIS/orca_nw_lib#79](https://github.com/STORDIS/orca_nw_lib/pull/79)
- Backend - [Issue in deletion of vlan properties -b- #40 #50](https://github.com/STORDIS/orca_backend/pull/50)
- Ui - [Issue in deletion of vlan properties - ui - #40 STORDIS/orca_ui#140](https://github.com/STORDIS/orca_ui/pull/140)

**Comment by kamalkrbh** [comment]
@vivek-metricdust , Test cases for update and delete of IP, SAG IP and description are missing.
