### ISSUE TITLE
MCLAG - member / domain id / gateway MAC issue

### ISSUE THREAD

**Issue by vivek-metricdust** [STORDIS/orca_backend#43]
- [x] The get api for mclag is giving all port channel data (mclag_members) which can be reduced to only lag_name
- [x] The get request needs domain id to give the members and if domain id is not provided its not giving members data which must be handled in backend.
- [x] configuration of gate way is made using a different api end point i.e "gateway_mac" that must be combined in the end point "device_mclag_list"

**Comment by rahul-1475** [comment]
orca_backend pr : https://github.com/STORDIS/orca_backend/pull/46
