### ISSUE TITLE
Docker orca_backend -Host Networking option not supported by default on Mac and Windows hence orca_backend is not reachable.

### ISSUE THREAD

**Issue by kamalkrbh** [STORDIS/orca_backend#55]
orca_backend is not reachable while running inside container on Mac or windows, Because host networking is not supported by default on those platform, hence --net="host" option supplied in docker command remains ineffective (silently). Althoug host networking can be enabled from settings - 

![Image](https://github.com/user-attachments/assets/deb5e9a6-3a8c-41f9-abad-598281a07608)

But still a better approach would be to create a separate network for orca containers so that they can speak to each other in a separate namespace without interfering with host network. Also --net="host" isn't considered to be the safest approach while runnign a container.
A separate Network can be created as follows -
docker network create orca_container_network
Then add all 3 containers orca_ui, orca_backend and neo4j to same network while starting like -
docker run --network=orca_container_network .......................
While runinng for example orca_backend container the neo4j address can be suplied as env_var name = orca_neo4j (container name)
Document should be updated accordingly and should have both the approached with --net="host" and --network=orca_container_network , The later approach is recommended.

**Comment by vivek-metricdust** [comment]
Issue found:

when decor is running and if its stopped and re run or if we restart the decor container it will execute the super admin creation command and will prompt that the username is already taken and will stop there.

**Comment by rahul-1475** [comment]
pr link: https://github.com/STORDIS/orca_backend/pull/59

**Comment by kamalkrbh** [comment]
@rahul-1475 ,
There are even more aspects to it, for example – orca_ui should also start the doctor container in a similar way,
Also, how is it going to work if neo4j data base, orca_backend and orca UI containers running on different machines.

**Comment by kamalkrbh** [comment]
@rahul-1475  , May be if we always pass env_var for database url pointing to specific host_ip instead of using localhost then it will work in both the cases i.e. running all containers in 1 machine or multiple ones. Also then no need to create docker network either.
