### ISSUE TITLE
Portchannel put request results in 2 responses

### ISSUE THREAD

**Issue by vivek-metricdust** [STORDIS/orca_backend#58]
Put request for portchannel is resulting in 2 response from the backend 
Below is the response body received when api is called 
`[
    {
        "status": "success",
        "message": "PUT request successful"
    },
    "\n",
    {
        "status": "success",
        "message": "PUT request successful"
    }
]` 

this is resulting in 2 rows of logs in log Pannel which will make an impression of 2 request has been triggered.

**Comment by rahul-1475** [comment]
There were two responses in beause one response indicates that configuration added successfully and second confuguration indicates members are added successfuly.

**Comment by vivek-metricdust** [comment]
{
    "mgt_ip": "10.10.229.58",
    "lag_name": "PortChannel102",
    "admin_sts": "up",
    "mtu": 9100,
    "static": false,
    "fallback": false,
    "fast_rate": false,
    "graceful_shutdown_mode": "disable",
    "min_links": 1
}

This is the payload which does not have any members but still it results with 2 response

**Comment by kamalkrbh** [comment]
@rahul-1475 , Even if only access vlan are added its receiving 2 responses ?

**Comment by rahul-1475** [comment]
Issed fixed in pr: https://github.com/STORDIS/orca_backend/pull/62
