### ISSUE TITLE
Support for ZTP in ORCA - backend

### ISSUE THREAD

**Issue by kamalkrbh** [STORDIS/orca_backend#70]
# ZTP & DHCP Config

### orca_backend
- Ability to host the files in orca_backend (better make a new app) and make them accessible via http, (files need not to be protected by user password in the begining), For files being hosted a specific directory can be made within orca_backend project and should be included in .gitignore file.
- This option will require the release upgrade feature to do a small update, where user can either provide the image URL as it do it currently or it can also provide releases available in orca_backend. When user selects one of the releases available in orca_backend the respective http urls should be used on the device while doing release upgrade.
 
### orca_backend
- API to create and host one or more (with different names) ztp json files in orca. 
- Get API to return file name, content, http URL of one or more those files.

### orca_backend 
- PUT/GET APIs to get or save DHCP server(s) ssh credentials, API will receive server credentials which should be saved in sql DB. There could be multiple DHCP servers stored in the sql DB.
- API to directly get or update /etc/dhcp/dhcpd.conf on the dhcp server. dhcp server can be accessed via ssh.
Before saving the dhcpd.conf, a backup file should be created on the dhcp server itself . e.g. with the name dhcpd.conf.orca.<time_stamp>. orca_backend will not store dhcpd.conf or its backups, they remain only on dhcp server. API should be able to provide list of backups created and get/set of their content.
- Also there should be maximum number of backup files that can be created, lets say max 10(configurable). When max backup files has been created and a new backup file is created , the oldest backup file should be deleted (file rotation) on the dhcp server.
After writing the dhcpd.conf on the device, dhcpd daemon should be restarted, the command to restart should be passed to the API (default - sudo systemctl restart isc-dhcp-server)
- Before updating /etc/dhcp/dhcpd.conf on the device backend should check for json syntax validation if any ztp.json or so is provided in dhcpd.conf if validation failed backend should not write the file i ndhcp server and should throw an error.

### orca_backend 
prca_backend should schedule a thread to constantly read the /var/lib/dhcp/dhcpd.leases and /etc/dhcp/dhcpd.conf and look for which devices have sonic in their host names, and if the IPs of those devices is not discovered in ORCA, orca should return the IP and  MAC address of those devices those are aavaialble SONiC devices in the network but not yet discovered in orca.
Sample of /var/lib/dhcp/dhcpd.leases and /etc/dhcp/dhcpd.conf can be found online or from one of the dhcp server.

Related UI - [orca_ui #173](https://github.com/STORDIS/orca_ui/issues/173)

**Comment by kamalkrbh** [comment]
Following observed in demo -
- [ ] Checksum should be comapred before saving files (ztp & dhcp).
- [ ] 11 dhcp backups are created, should be 10.
- [ ] List of sorted dhcp backup files based on creation time should be returned to UI.
- [ ] Sample readonly templates for dhcp and ztp to be stored in ORCA server for user reference.
- [ ] Test case for oldest backup file removal.
- [ ] Functionality for renaming ztp files.

**Comment by rahul-1475** [comment]
- [ ] fix ssh connection error.
- [ ] remove authentication for downlaod
- [ ]  clean up templates.
