### ISSUE TITLE
Interface Primary/Secondary IP configuration.

### ISSUE THREAD

**Issue by kamalkrbh** [STORDIS/orca_backend#74]
Currently in the SubInterface model has only one property ip_address, but while assiging IP to an interface there is another property should be taken into consideration primary/secondary, in order to keep it sligned with openconfig model another boolean property "secondary" should be added to SubInterface model.
Hence each IP configuration should take additional property "secondary" which by default should be considered to false.

**Comment by rahul-1475** [comment]
orca_backend pr: https://github.com/STORDIS/orca_backend/pull/79
orca_nw_lib pr: https://github.com/STORDIS/orca_nw_lib/pull/99

**Comment by vivek-metricdust** [comment]
issue found - when already configured ip is changed and tried to update it is adding the value as new IP instead of updating the current IP
