### ISSUE TITLE
Discovery Enhancements - Incase of subnet addrtess provided.

### ISSUE THREAD

**Issue by kamalkrbh** [STORDIS/orca_backend#75]
In case when a user have provided a subnet address , Instead of right away triggering discovery, first the user should be provided with list of sonic devices with system info so that user can select one or more or all the devices from the list which can then be discovered.
Also lets fix the network bit to 22 as lesser bits will result into more IPs to scan for. So any network address which has mask bits less than 22 should be discarded.

**Comment by rahul-1475** [comment]
This issue is fixed in [#87](https://github.com/STORDIS/orca_backend/issues/87) , celery handels network scan when network ip is given.
